Week-5 - Json Converter implementation + test implementation
Locomody/scala-course-2022-spring pull request #5
Opened 2022-06-16 10:56 UTC by Locomody

2022-06-21 10:43 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week5/homework/givens.scala
> +    def encode(src: List[T]): String = "[" + src.foldLeft(List[String]()) {(acc, src) => acc :+ encoder.encode(src)}.mkString(", ") + "]"
There is an extended version of `.mkString(", ")` `.mkString("[", ",", "]") so the fold can be simplified with map.
But it's not an issue.

2022-06-21 10:44 UTC, IgorWolkov requested changes
Looks like you have one failed test case.

2022-06-21 10:46 UTC, Locomody commented on src/test/scala/karazin/scala/users/group/week5/homework/GivensSuite.scala
> +        .encode(117), "200"
oh sure, it fails)

2022-06-21 10:50 UTC, Locomody commented
> 
Fixed

2022-06-27 10:19 UTC, IgorWolkov approved these changes
Good job.

2022-06-27 10:20 UTC, merged